/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xryusha_onlinedebug_runtime_util_remote_StackMiner */

#ifndef _Included_xryusha_onlinedebug_runtime_util_remote_StackMiner
#define _Included_xryusha_onlinedebug_runtime_util_remote_StackMiner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xryusha_onlinedebug_runtime_util_remote_StackMiner
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xryusha_onlinedebug_runtime_util_remote_StackMiner_init
  (JNIEnv *, jclass);

/*
 * Class:     xryusha_onlinedebug_runtime_util_remote_StackMiner
 * Method:    extract
 * Signature: (Ljava/util/List;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_xryusha_onlinedebug_runtime_util_remote_StackMiner_extract
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     xryusha_onlinedebug_runtime_util_remote_StackMiner
 * Method:    setValue
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_xryusha_onlinedebug_runtime_util_remote_StackMiner_setValue
  (JNIEnv *, jclass, jstring, jobject, jint);

/*
 * Class:     xryusha_onlinedebug_runtime_util_remote_StackMiner
 * Method:    enforceReturn
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_xryusha_onlinedebug_runtime_util_remote_StackMiner_enforceReturn
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
